### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#54]
When I try to log in in Firefox, I get the ORCID authorization request screen, and then when I approve the authorization request, I get redirected to this screen:

![screen shot 2015-02-03 at 6 14 14 pm](https://cloud.githubusercontent.com/assets/3872825/6031815/7ae0e430-abd0-11e4-9241-17b0193bb0c6.png)

**Comment by stuartlynn** [comment]
New user creation seems to be failing on heroku with this error 

2015-02-03T23:28:14.333260+00:00 app[web.1]: ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
2015-02-03T23:28:14.333262+00:00 app[web.1]:   app/models/user.rb:18:in `from_omniauth'
2015-02-03T23:28:14.333264+00:00 app[web.1]:   app/controllers/sessions_controller.rb:8:in `create'
